---
title: "aser_2018_investigation"
author: "Zack Arno"
date: "9/17/2020"
output: html_document
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(extrafont)
knitr::opts_chunk$set(warning = FALSE,
               message = FALSE,
               echo    = FALSE,
               fig.align  = "center",
               fig.width = 7.25,
               fig.height = 6)


```

<style type="text/css"> 
code, pre { 
    font-family: Fira Code, Iosevka, Hack, monospace; 
} 
</style>

```{r, include=F}

df<-haven::read_sav("../inputs/Final dataset-ASER plus - 19082019.sav")
df2<-df %>% 
  mutate(Date= as_date(Date))

df2 %>% 
  filter(is.na(Date)) %>% nrow()
# these seem like more realistic dates
df2 %>% 
  filter(!is.na(Date)) %>% 
  filter(Date>as_date("2016-01-01"),Date<Sys.Date()) %>% 
  pull(Date) %>% range()

df2 %>% 
  filter(!is.na(Date)) %>% 
  filter(Date>as_date("2016-01-01"),Date<Sys.Date()) %>% 
  filter(Date>as_date("2019-01-01")) %>% 
  select(Date) %>% print(n=nrow(.))

df2 %>% 
  filter(!is.na(Date)) %>% 
  filter(Date>as_date("2016-01-01"),Date<Sys.Date()) %>% 
  # filter(Date>as_date("2019-01-01")) %>% 
  group_by(centername) %>% 
  select(Date,teacherhost_1) 

initial_dataset_only_valid_dates<-df2 %>% mutate_all(~trimws(.)) %>% 
  mutate_if(is.character, funs(na_if(., ""))) 



```

## Data Summary


```{r cars}
skimr::skim(initial_dataset_only_valid_dates)
```



```{r pressure, echo=FALSE, eval= F}
plot(pressure)
```


